### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by 98Kstar** [whydee86/PlayWithDefender#1]
ubuntu@10-31-23-192:~/cs/PlayWithDefender$ nim c -x -f FDefender.nim
Hint: used config file '/home/ubuntu/.choosenim/toolchains/nim-1.6.4/config/nim.cfg' [Conf]
Hint: used config file '/home/ubuntu/.choosenim/toolchains/nim-1.6.4/config/config.nims' [Conf]
..........................................................
/home/ubuntu/cs/PlayWithDefender/RegHelper.nim(2, 8) Error: cannot open file: winregistry

**Comment by whydee86** [comment]
nimble install winregistry
