### ISSUE TITLE
MAC OS没法编译成功

### ISSUE THREAD

**Issue by en0th** [whydee86/PlayWithDefender#2]
![image](https://user-images.githubusercontent.com/67619247/159222078-75ac8463-2e97-49f0-8584-d6e809d28ea4.png)
忽略文件 /Users/en0th/.nimble/pkgs/winim-3.8.0/winim/lib/winim64.res
最后生成的并不是exe

**Comment by whydee86** [comment]
It supports only windows, you can try cross-compile for windows.
What flags do you use?
